### PR TITLE
Adapt to master -> main renaming

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Review by willclarktech — APPROVED** [review]
Looks good. Will we also need to update references to other repos?

**Comment by webmaster128** [comment]
> Will we also need to update references to other repos?

What kind of references? From out text/comments to other repos? I'd only update those is the target choses to rename their default branch. But even then GitHub implemented some nice redirects (check e.g. https://github.com/cosmos/cosmjs/tree/master/packages/cli), so I don't see any pressure.

**Comment by willclarktech** [comment]
> What kind of references? From out text/comments to other repos?

Yeah, but in particular other repos we control.

**Comment by webmaster128** [comment]
Yeah I think we should update other repos as well.

**Pull request merged**
