### PR TITLE
Fix decoding of events with no attributes

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #1198

### CODE REVIEW

**Comment by holyxiaoxin** [comment]
Could you also help publish this next tag? thanks.

**Comment by webmaster128** [comment]
> Could you also help publish this next tag? thanks.

What about backporting this to 0.28.x instead? Or do you need other 0.29 features?

**Comment by holyxiaoxin** [comment]
> > Could you also help publish this next tag? thanks.
> 
> What about backporting this to 0.28.x instead? Or do you need other 0.29 features?

backporting to 0.28.x is good! thanks

**Comment by webmaster128** [comment]
Published as part of 0.28.10

**Pull request merged**
