### PR TITLE
Update signingstargateclient.ts

### PR DESCRIPTION
**Pull request by blackpanther1881**
removing extra space in messageTimeout

### CODE REVIEW

**Comment by puneet2019** [comment]
@webmaster128 can we also add `MsgCreateVestingAccount` to the default registry? 
`["/cosmos.vesting.v1beta1.MsgCreateVestingAccount", vestingTx.MsgCreateVestingAccount]`

**Comment by webmaster128** [comment]
@puneet2019 I think so, yes. But let's track this independently. Ideally we write a test for it first to avoid bugs like this one.

**Review by webmaster128 — COMMENTED** [review]
Thanks. Could you add a CHNAGLOG entry for this in the `### Fixed` section of `## [Unreleased]`?

**Comment by blackpanther1881** [comment]
@webmaster128 added CHNAGLOG

**Comment by webmaster128** [comment]
Could you do that in the same PR to have everything together? Also please note you put it in the 0.26.1 section that is already released.

**Review by webmaster128 — APPROVED** [review]

**Pull request merged**
