### PR TITLE
Fix `Decimal` can be constructed with a negative atomics

### PR DESCRIPTION
**Pull request by tien**

### CODE REVIEW

**Review by webmaster128 — COMMENTED** [review]
Nice catch! The atomics string should checked more strictly.

Can you use

```ts
    if (!atomics.match(/^[0-9]+$/)) {
      throw new Error("Invalid string format. Only non-negative integers in decimal representation suppored.");
    }
```

instead?

**Comment by tien** [comment]
@webmaster128 sure thing, I have updated the PR accordingly.

**Review by webmaster128 — APPROVED** [review]
Thank you!

Will merge as part of #1195

**Comment by webmaster128** [comment]
Shipped as part of CosmJS 0.29.0

**Pull request merged**
