### PR TITLE
fix: Add ibc, liquidity pool (and more) denom support to parseCoins()

### PR DESCRIPTION
**Pull request by clockworkgr**
As per: https://github.com/cosmos/cosmos-sdk/blob/master/types/coin.go#L637

### CODE REVIEW

**Comment by webmaster128** [comment]
Thanks for bringing this up. Where/how do you use `parseCoins`? It seems to be unused internally.

We duplicate that logic in `GasPrice.fromString`, which is implemented twice with different patterns in launchpad and stargate.

**Comment by clockworkgr** [comment]
I use it in quite a few places since our app uses the `1234uatom` format a fair bit.

Tbh I can't remember where/when I first came across the existence of parseCoins but I've been using it since for that purpose

**Comment by webmaster128** [comment]
If you only need one, could you use `coin(value, "denom")` or `coins(value, "denom")` instead? The first one returns a `Coin` the second one a `Coin[]`. This contains much fewer logic and checks.

In order to make `parseCoins` Stargate ready, we should have a Stargate specific version:
- Remove the re-export `parseCoins` from `packages/proto-signing/src/index.ts`
- Re-implement `parseCoins` in `packages/proto-signing/src/coins.ts` and export in `packages/proto-signing/src/index.ts`

**Comment by webmaster128** [comment]
@clockworkgr could you have a look at https://github.com/cosmos/cosmjs/pull/845? I think this is what you are looking for.

**Pull request closed without merging**
